# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.restaurant import Restaurant  # noqa: F401,E501
from swagger_server import util


class RestaurantListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, restaurants: List[Restaurant]=None):  # noqa: E501
        """RestaurantListResponse - a model defined in Swagger

        :param restaurants: The restaurants of this RestaurantListResponse.  # noqa: E501
        :type restaurants: List[Restaurant]
        """
        self.swagger_types = {
            'restaurants': List[Restaurant]
        }

        self.attribute_map = {
            'restaurants': 'restaurants'
        }

        self._restaurants = restaurants

    @classmethod
    def from_dict(cls, dikt) -> 'RestaurantListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RestaurantListResponse of this RestaurantListResponse.  # noqa: E501
        :rtype: RestaurantListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def restaurants(self) -> List[Restaurant]:
        """Gets the restaurants of this RestaurantListResponse.


        :return: The restaurants of this RestaurantListResponse.
        :rtype: List[Restaurant]
        """
        return self._restaurants

    @restaurants.setter
    def restaurants(self, restaurants: List[Restaurant]):
        """Sets the restaurants of this RestaurantListResponse.


        :param restaurants: The restaurants of this RestaurantListResponse.
        :type restaurants: List[Restaurant]
        """
        if restaurants is None:
            raise ValueError("Invalid value for `restaurants`, must not be `None`")  # noqa: E501

        self._restaurants = restaurants
